language: node_js
node_js:
  - 'stable'

env:
  global:
    - CC_TEST_REPORTER_ID=6226331d6756b57ab4005e4a

install: yarn install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
  - yarn install
  - yarn test

after_success:
  - yarn run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

